[project]
name = "storytime"
version = "0.1.0"
description = "Children's book illustration generator using LangChain and OpenRouter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # Web framework
    "streamlit>=1.40.0",
    
    # AI and Google GenAI
    "google-genai>=0.8.0",
    
    # Data models and validation
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
    
    # Image processing
    "pillow>=10.0.0",
    
    # PDF processing
    "pypdf>=4.0.0",
    "reportlab>=4.0.0",
    "pdfplumber>=0.10.0",
    
    # Language support
    "langdetect>=1.0.0",
    
    # HTTP requests
    "requests>=2.31.0",
    
    # Utilities
    "python-dotenv>=1.0.0"
]

[dependency-groups]
dev = [
    "watchdog>=6.0.0",
]
